
create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name pspin_clk_wiz

# 50 MHz clock for PsPIN
# set_property -dict [list \
    CONFIG.PRIM_IN_FREQ {250} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {50} \
    CONFIG.CLKIN1_JITTER_PS {40.0} \
    CONFIG.MMCM_DIVCLK_DIVIDE {5} \
    CONFIG.MMCM_CLKFBOUT_MULT_F {24.000} \
    CONFIG.MMCM_CLKIN1_PERIOD {4.000} \
    CONFIG.MMCM_CLKIN2_PERIOD {10.0} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F {24.000} \
    CONFIG.CLKOUT1_JITTER {153.164} \
    CONFIG.CLKOUT1_PHASE_ERROR {154.678}
# ] [get_ips pspin_clk_wiz]

# 45 MHz clock for PsPIN
# set_property -dict [list \
    CONFIG.PRIM_IN_FREQ {250} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {45} \
    CONFIG.CLKIN1_JITTER_PS {40.0} \
    CONFIG.MMCM_DIVCLK_DIVIDE {25} \
    CONFIG.MMCM_CLKFBOUT_MULT_F {120.375} \
    CONFIG.MMCM_CLKIN1_PERIOD {4.000} \
    CONFIG.MMCM_CLKIN2_PERIOD {10.0} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F {26.750} \
    CONFIG.CLKOUT1_JITTER {230.743} \
    CONFIG.CLKOUT1_PHASE_ERROR {351.446}
# ] [get_ips pspin_clk_wiz]

# 40 MHz clock for PsPIN
set_property -dict [list \
    CONFIG.PRIM_IN_FREQ {250} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {40} \
    CONFIG.CLKIN1_JITTER_PS {40.0} \
    CONFIG.MMCM_DIVCLK_DIVIDE {5} \
    CONFIG.MMCM_CLKFBOUT_MULT_F {24.000} \
    CONFIG.MMCM_CLKIN1_PERIOD {4.000} \
    CONFIG.MMCM_CLKIN2_PERIOD {10.0} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F {30.000} \
    CONFIG.CLKOUT1_JITTER {159.975} \
    CONFIG.CLKOUT1_PHASE_ERROR {154.678}
] [get_ips pspin_clk_wiz]
