site_name: PsPIN
repo_url: https://github.com/spcl/pspin
theme: 
    name: material 

nav:
    - Home: 'index.md'
    - Getting started:
        - Docker image: 'docker.md'
        - Manual installation: 'compile.md'
        - Running examples: 'examples.md'
    - Testing your own handlers: 
        - Minimal handler: 'handlers_minimal.md'
        - sPIN API: 'api.md'
        - Simulation driver: 'sim_driver.md'

